/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/clinton/cs1567_ws/src/cs1567p0/srv/ConstantCommand.srv
 *
 */


#ifndef CS1567P0_MESSAGE_CONSTANTCOMMAND_H
#define CS1567P0_MESSAGE_CONSTANTCOMMAND_H

#include <ros/service_traits.h>


#include <cs1567p0/ConstantCommandRequest.h>
#include <cs1567p0/ConstantCommandResponse.h>


namespace cs1567p0
{

struct ConstantCommand
{

typedef ConstantCommandRequest Request;
typedef ConstantCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConstantCommand
} // namespace cs1567p0


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cs1567p0::ConstantCommand > {
  static const char* value()
  {
    return "304dd3f6ef6b49ed507d4f75dde10aeb";
  }

  static const char* value(const ::cs1567p0::ConstantCommand&) { return value(); }
};

template<>
struct DataType< ::cs1567p0::ConstantCommand > {
  static const char* value()
  {
    return "cs1567p0/ConstantCommand";
  }

  static const char* value(const ::cs1567p0::ConstantCommand&) { return value(); }
};


// service_traits::MD5Sum< ::cs1567p0::ConstantCommandRequest> should match 
// service_traits::MD5Sum< ::cs1567p0::ConstantCommand > 
template<>
struct MD5Sum< ::cs1567p0::ConstantCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cs1567p0::ConstantCommand >::value();
  }
  static const char* value(const ::cs1567p0::ConstantCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cs1567p0::ConstantCommandRequest> should match 
// service_traits::DataType< ::cs1567p0::ConstantCommand > 
template<>
struct DataType< ::cs1567p0::ConstantCommandRequest>
{
  static const char* value()
  {
    return DataType< ::cs1567p0::ConstantCommand >::value();
  }
  static const char* value(const ::cs1567p0::ConstantCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cs1567p0::ConstantCommandResponse> should match 
// service_traits::MD5Sum< ::cs1567p0::ConstantCommand > 
template<>
struct MD5Sum< ::cs1567p0::ConstantCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cs1567p0::ConstantCommand >::value();
  }
  static const char* value(const ::cs1567p0::ConstantCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cs1567p0::ConstantCommandResponse> should match 
// service_traits::DataType< ::cs1567p0::ConstantCommand > 
template<>
struct DataType< ::cs1567p0::ConstantCommandResponse>
{
  static const char* value()
  {
    return DataType< ::cs1567p0::ConstantCommand >::value();
  }
  static const char* value(const ::cs1567p0::ConstantCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CS1567P0_MESSAGE_CONSTANTCOMMAND_H
